from pydantic import BaseModel, Field
from dotenv import load_dotenv
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
load_dotenv()
talkingModel = HuggingFaceEndpoint(repo_id="deepseek-ai/DeepSeek-V4-Pro-0813",task ="text-generation")
model = ChatHuggingFace(llm=talkingModel)

class Person(BaseModel):
    name: str = Field(description="Name of the person")
    age: int = Field(gt=18,description="Age of the person")
    city: str = Field(description="Name of the city this person belongs to")


parser = PydanticOutputParser(pydantic_object=Person)

template = PromptTemplate(template='Generate the name age city of the movie character from {place} \n {format_instructions}',
                          input_variables=['place'],
                          partial_variables={'format_instructions':parser.get_format_instructions}) 
# format_instructions is the text generated by the output parser that tells the LLM exactly what format it must return.

# prompt = template.invoke()


# print('prompt \n')
# print(prompt)


chain  = template | model | parser
# result = model.invoke(prompt)
result = chain.invoke({'place':'india'})
print(result)